steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/email-processor', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/email-processor']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'email-processor'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/email-processor'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--set-env-vars'
      - 'PROJECT_ID=${PROJECT_ID},REGION=${_REGION},SUPABASE_URL=${_SUPABASE_URL},SUPABASE_SERVICE_ROLE_KEY=${_SUPABASE_SERVICE_ROLE_KEY},META_ACCESS_TOKEN=${_META_ACCESS_TOKEN},META_PAGE_ID=${_META_PAGE_ID},META_B2B_FORM_ID=${_META_B2B_FORM_ID},META_B2C_FORM_ID=${_META_B2C_FORM_ID},FACEBOOK_SHEET_ID=${_FACEBOOK_SHEET_ID},FACEBOOK_B2B_SHEET_ID=${_FACEBOOK_B2B_SHEET_ID},LINE_CHANNEL_ACCESS_TOKEN=${_LINE_CHANNEL_ACCESS_TOKEN},LINE_GROUP_ID=${_LINE_GROUP_ID},LINE_CHANNEL_SECRET=${_LINE_CHANNEL_SECRET},LINE_GROUP_ID_B2B=${_LINE_GROUP_ID_B2B},LINE_GROUP_ID_B2C=${_LINE_GROUP_ID_B2C},LINE_GROUP_ID_CLASSPASS=${_LINE_GROUP_ID_CLASSPASS},LINE_GROUP_ID_WEBRESOS=${_LINE_GROUP_ID_WEBRESOS},LABEL_CLASSPASS=Web Leads (ClassPass),LABEL_WEB=Web Leads,LABEL_RESOS=Web Leads (ResOS),LABEL_FACEBOOK=Web Leads (Facebook),LABEL_COMPLETED=Web Leads - completed,VERTEX_LOCATION=${_VERTEX_LOCATION},ENABLE_LLM_SPAM_DETECTION=${_ENABLE_LLM_SPAM_DETECTION}'
      - '--service-account'
      - 'email-processor-sa@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--timeout'
      - '540s'

images:
  - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/email-processor'

substitutions:
  _REGION: asia-southeast1
  _SUPABASE_URL: # Set this in Cloud Build trigger
  _SUPABASE_SERVICE_ROLE_KEY: # Set this in Cloud Build trigger
  _META_ACCESS_TOKEN: # Set this in Cloud Build trigger
  _META_PAGE_ID: # Set this in Cloud Build trigger
  _META_B2B_FORM_ID: # Set this in Cloud Build trigger
  _META_B2C_FORM_ID: # Set this in Cloud Build trigger
  _FACEBOOK_SHEET_ID: # Set this in Cloud Build trigger
  _FACEBOOK_B2B_SHEET_ID: # Set this in Cloud Build trigger
  _LINE_CHANNEL_ACCESS_TOKEN: # Set this in Cloud Build trigger
  _LINE_GROUP_ID: # Set this in Cloud Build trigger
  _LINE_CHANNEL_SECRET: # Set this in Cloud Build trigger
  _LINE_GROUP_ID_B2B: # Set this in Cloud Build trigger
  _LINE_GROUP_ID_B2C: # Set this in Cloud Build trigger
  _LINE_GROUP_ID_CLASSPASS: # Set this in Cloud Build trigger
  _LINE_GROUP_ID_WEBRESOS: # Set this in Cloud Build trigger
  _VERTEX_LOCATION: us-central1 # Set this in Cloud Build trigger
  _ENABLE_LLM_SPAM_DETECTION: 'true' # Set this in Cloud Build trigger