steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/email-processor', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/email-processor']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'email-processor'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/email-processor'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--set-env-vars'
      - 'PROJECT_ID=${PROJECT_ID},REGION=${_REGION},META_ACCESS_TOKEN=${_META_ACCESS_TOKEN},META_PAGE_ID=${_META_PAGE_ID},META_B2B_FORM_ID=${_META_B2B_FORM_ID},META_B2C_FORM_ID=${_META_B2C_FORM_ID}'
      - '--service-account'
      - 'email-processor-sa@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--timeout'
      - '540s'

images:
  - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/email-processor'

substitutions:
  _REGION: asia-southeast1
  _META_ACCESS_TOKEN: # Set this in Cloud Build trigger
  _META_PAGE_ID: # Set this in Cloud Build trigger
  _META_B2B_FORM_ID: # Set this in Cloud Build trigger
  _META_B2C_FORM_ID: # Set this in Cloud Build trigger