// Data services ported from src/services/{customerService,bookingService,emailTrackingService}.js.
// Behavior (matching priority, bay assignment, booking ID format, dedup semantics)
// is preserved from the Node implementation.

import type { SupabaseClient } from 'npm:@supabase/supabase-js@2';
import { calculateEndTime24, log, parseTimeToStandard } from './utils.ts';

// deno-lint-ignore no-explicit-any
type Row = Record<string, any>;

// ---------------------------------------------------------------------------
// CustomerService
// ---------------------------------------------------------------------------

export class CustomerService {
  constructor(private supabase: SupabaseClient) {}

  normalizePhone(phoneInput: string | null | undefined): string {
    if (!phoneInput) return '';
    let digits = phoneInput.replace(/[^0-9]/g, '');
    if (digits.startsWith('66')) digits = digits.substring(2);
    if (digits.startsWith('0')) digits = digits.substring(1);
    return digits.substring(Math.max(0, digits.length - 9));
  }

  async findByPhone(phoneNumber: string): Promise<Row | null> {
    const normalizedPhone = this.normalizePhone(phoneNumber);
    if (!normalizedPhone || normalizedPhone.length < 9) {
      log('WARN', 'Phone number too short for matching', { normalizedLength: normalizedPhone.length });
      return null;
    }
    const { data, error } = await this.supabase
      .from('customers')
      .select('*')
      .eq('normalized_phone', normalizedPhone)
      .eq('is_active', true)
      .limit(1);
    if (error) throw new Error(`findByPhone failed: ${error.message}`, { cause: error });
    return data && data.length > 0 ? data[0] : null;
  }

  async findByEmail(email: string): Promise<Row | null> {
    if (!email) return null;
    const { data, error } = await this.supabase
      .from('customers')
      .select('*')
      .ilike('email', email)
      .eq('is_active', true)
      .limit(1);
    if (error) throw new Error(`findByEmail failed: ${error.message}`, { cause: error });
    return data && data.length > 0 ? data[0] : null;
  }

  async findByFuzzyName(name: string, threshold = 0.9): Promise<Row | null> {
    if (!name) return null;
    const { data, error } = await this.supabase.rpc('find_customers_by_fuzzy_name', {
      search_name: name,
      min_similarity: threshold,
    });
    if (error) throw new Error(`findByFuzzyName failed: ${error.message}`, { cause: error });
    if (data && data.length === 1 && data[0].similarity >= threshold) {
      return data[0];
    }
    if (data && data.length > 1) {
      log('WARN', 'Multiple customers found with similar names - ambiguous match', {
        matchCount: data.length,
      });
    }
    return null;
  }

  async getOrCreateCustomer(
    customerData: { name: string; phone?: string | null; email?: string | null },
    allowFuzzyName = false,
  ): Promise<{ customer: Row; isNew: boolean; matchedBy: string | null }> {
    const { name, phone, email } = customerData;

    if (phone) {
      const customer = await this.findByPhone(phone);
      if (customer) return { customer, isNew: false, matchedBy: 'phone' };
    }
    if (email) {
      const customer = await this.findByEmail(email);
      if (customer) return { customer, isNew: false, matchedBy: 'email' };
    }
    if (allowFuzzyName && name) {
      const threshold = parseFloat(Deno.env.get('FUZZY_NAME_THRESHOLD') || '0.9');
      const customer = await this.findByFuzzyName(name, threshold);
      if (customer) return { customer, isNew: false, matchedBy: 'fuzzy_name' };
    }

    const customer = await this.createCustomer(customerData);
    return { customer, isNew: true, matchedBy: null };
  }

  async createCustomer(customerData: { name: string; phone?: string | null; email?: string | null }): Promise<Row> {
    const { name, phone, email } = customerData;
    if (!name) throw new Error('Customer name is required');
    if (!phone && !email) throw new Error('At least one contact method (phone or email) is required');

    const newCustomer = {
      // customer_code is auto-generated by the trigger_set_customer_code trigger
      customer_name: name,
      contact_number: phone || null,
      email: email || null,
      normalized_phone: phone ? this.normalizePhone(phone) : null,
      is_active: true,
      preferred_contact_method: phone ? 'Phone' : 'Email',
    };

    const { data, error } = await this.supabase
      .from('customers')
      .insert(newCustomer)
      .select()
      .single();

    if (error) {
      if (error.code === '23505' && error.message.includes('normalized_phone')) {
        throw new Error('DUPLICATE_PHONE');
      }
      throw new Error(`createCustomer failed: ${error.message}`, { cause: error });
    }

    log('INFO', 'Customer created', {
      customerId: data.id,
      customerCode: data.customer_code,
    });
    return data;
  }
}

// ---------------------------------------------------------------------------
// BookingService
// ---------------------------------------------------------------------------

const BAYS = {
  SOCIAL: ['Bay 2', 'Bay 3', 'Bay 1'], // Preference order (Bay 1 is Bar)
  AI: ['Bay 4'],
};
const MAX_PEOPLE_SOCIAL = 5;
const DEFAULT_GUEST_USER_ID = '0eb32c8b-b2eb-4c8d-ba19-fc4f8e15f4c7';

export interface CreateBookingInput {
  customerId?: string | null;
  customerName: string;
  customerPhone?: string | null;
  customerEmail?: string | null;
  date: string;
  startTime: string;
  duration: number;
  numberOfPeople: number;
  bay?: string | null;
  customerContactedVia?: string;
  reservationKey?: string | null;
  customerNotes?: string | null;
  isNewCustomer?: boolean;
}

export class BookingService {
  constructor(private supabase: SupabaseClient) {}

  parseTimeToStandard(timeString: string): string {
    return parseTimeToStandard(timeString);
  }

  async isBayAvailable(bay: string, date: string, startTime: string, duration: number): Promise<boolean> {
    const endTime = calculateEndTime24(startTime, duration);

    const { data, error } = await this.supabase
      .from('bookings')
      .select('id, start_time, duration')
      .eq('bay', bay)
      .eq('date', date)
      .eq('status', 'confirmed');
    if (error) throw new Error(`isBayAvailable query failed: ${error.message}`, { cause: error });

    for (const booking of data || []) {
      const existingStart = booking.start_time.slice(0, 5);
      const existingEnd = calculateEndTime24(existingStart, booking.duration);
      const hasOverlap = (
        (startTime >= existingStart && startTime < existingEnd) ||
        (endTime > existingStart && endTime <= existingEnd) ||
        (startTime <= existingStart && endTime >= existingEnd)
      );
      if (hasOverlap) return false;
    }
    return true;
  }

  async assignBay(numberOfPeople: number, date: string, startTime: string, duration: number): Promise<string | null> {
    let bayPreferences: string[];
    if (numberOfPeople === 1) {
      bayPreferences = [...BAYS.AI, ...BAYS.SOCIAL];
    } else if (numberOfPeople === 2) {
      bayPreferences = [...BAYS.SOCIAL, ...BAYS.AI];
    } else if (numberOfPeople <= MAX_PEOPLE_SOCIAL) {
      bayPreferences = BAYS.SOCIAL;
    } else {
      log('WARN', 'Party size exceeds maximum capacity', { numberOfPeople });
      return null;
    }

    for (const bay of bayPreferences) {
      if (await this.isBayAvailable(bay, date, startTime, duration)) {
        return bay;
      }
    }
    log('WARN', 'No bays available for requested time slot', { date, startTime, duration, numberOfPeople });
    return null;
  }

  async checkAvailability(date: string, startTime: string, duration: number, numberOfPeople: number):
    Promise<{ available: boolean; bay: string | null }> {
    const standardTime = parseTimeToStandard(startTime);
    const bay = await this.assignBay(numberOfPeople, date, standardTime, duration);
    return { available: bay !== null, bay };
  }

  generateBookingId(date: string): string {
    // Format: BK + YYMMDD + 4 random uppercase alphanumeric characters (matches lengolf-forms)
    const dateStr = date.replace(/-/g, '').substring(2);
    const randomSuffix = Math.random().toString(36).substring(2, 6).toUpperCase();
    return `BK${dateStr}${randomSuffix}`;
  }

  async hasBookingHistory(customerId: string): Promise<boolean> {
    const { count, error } = await this.supabase
      .from('bookings')
      .select('id', { count: 'exact', head: true })
      .eq('customer_id', customerId)
      .neq('status', 'cancelled');
    if (error) {
      log('WARN', 'Failed to check booking history, defaulting to existing customer', {
        customerId,
        error: error.message,
      });
      return true; // fail-closed: assume existing customer on error
    }
    return (count ?? 0) > 0;
  }

  async createBooking(input: CreateBookingInput): Promise<Row> {
    const {
      customerId, customerName, customerPhone, customerEmail,
      date, startTime, duration, numberOfPeople, bay,
      customerContactedVia, reservationKey = null, customerNotes = null,
      isNewCustomer = false,
    } = input;

    if (!customerName || (!customerPhone && !customerEmail) || !date || !startTime || !duration || !numberOfPeople) {
      throw new Error('Missing required booking fields');
    }

    // Generate dummy phone if missing (format: 0000 + MMDD + random 4 digits)
    let finalPhoneNumber = customerPhone;
    if (!finalPhoneNumber) {
      const today = new Date();
      const mmdd = String(today.getUTCMonth() + 1).padStart(2, '0') + String(today.getUTCDate()).padStart(2, '0');
      const random = String(Math.floor(Math.random() * 10000)).padStart(4, '0');
      finalPhoneNumber = `0000${mmdd}${random}`;
    }

    const standardStartTime = parseTimeToStandard(startTime);

    let assignedBay = bay;
    if (!assignedBay) {
      assignedBay = await this.assignBay(numberOfPeople, date, standardStartTime, duration);
      if (!assignedBay) throw new Error('NO_BAY_AVAILABLE');
    } else if (!(await this.isBayAvailable(assignedBay, date, standardStartTime, duration))) {
      throw new Error(`Bay ${assignedBay} is not available for requested time`);
    }

    const newBooking = {
      id: this.generateBookingId(date),
      user_id: DEFAULT_GUEST_USER_ID,
      customer_id: customerId || null,
      name: customerName,
      phone_number: finalPhoneNumber,
      email: customerEmail || '',
      date,
      start_time: standardStartTime,
      duration,
      number_of_people: numberOfPeople,
      bay: assignedBay,
      booking_type: customerContactedVia === 'ClassPass' ? 'ClassPass' : 'Normal Bay Rate',
      status: 'confirmed',
      customer_contacted_via: customerContactedVia || 'Email Automation',
      reservation_key: reservationKey,
      customer_notes: customerNotes,
      is_new_customer: Boolean(isNewCustomer),
      updated_by_type: 'system',
      updated_by_identifier: 'Email Automation',
    };

    const { data, error } = await this.supabase
      .from('bookings')
      .insert(newBooking)
      .select()
      .single();
    if (error) throw new Error(`createBooking failed: ${error.message}`, { cause: error });

    log('INFO', 'Booking created', {
      bookingId: data.id,
      date: data.date,
      startTime: data.start_time,
      bay: data.bay,
    });
    return data;
  }

  async cancelBooking(bookingId: string, reason: string, cancelledBy = 'Email Automation'): Promise<Row> {
    const { data, error } = await this.supabase
      .from('bookings')
      .update({
        status: 'cancelled',
        cancelled_by_type: 'system',
        cancelled_by_identifier: cancelledBy,
        cancellation_reason: reason,
      })
      .eq('id', bookingId)
      .select()
      .single();
    if (error) throw new Error(`cancelBooking failed: ${error.message}`, { cause: error });
    log('INFO', 'Booking cancelled', { bookingId, reason });
    return data;
  }

  async findBookingByReservationKey(reservationKey: string): Promise<Row | null> {
    const { data, error } = await this.supabase
      .from('bookings')
      .select('*')
      .eq('reservation_key', reservationKey)
      .eq('status', 'confirmed')
      .order('created_at', { ascending: false })
      .limit(1);
    if (error) throw new Error(`findBookingByReservationKey failed: ${error.message}`, { cause: error });
    return data && data.length > 0 ? data[0] : null;
  }

  async findBookingByDetails(
    customerName: string | null,
    phone: string | null,
    email: string | null,
    date: string,
    startTime: string,
    source: string | null = null,
  ): Promise<Row | null> {
    const standardStartTime = parseTimeToStandard(startTime);

    let query = this.supabase
      .from('bookings')
      .select('*')
      .eq('status', 'confirmed')
      .eq('date', date)
      .eq('start_time', standardStartTime);
    if (source) query = query.eq('customer_contacted_via', source);

    const { data, error } = await query;
    if (error) throw new Error(`findBookingByDetails failed: ${error.message}`, { cause: error });
    if (!data || data.length === 0) return null;

    const matches = data.filter((booking: Row) => {
      const phoneMatch = phone && booking.phone_number?.includes(phone);
      const emailMatch = email && booking.email && booking.email.toLowerCase() === email.toLowerCase();
      const nameMatch = customerName && booking.name?.toLowerCase().includes(customerName.toLowerCase());
      return phoneMatch || emailMatch || nameMatch;
    });

    if (matches.length === 0) return null;
    if (matches.length > 1) {
      log('WARN', 'Multiple bookings found matching criteria - ambiguous', {
        date,
        startTime: standardStartTime,
        matchCount: matches.length,
      });
      return null;
    }
    return matches[0];
  }
}

// ---------------------------------------------------------------------------
// EmailTrackingService
// ---------------------------------------------------------------------------

export type SourceType = 'classpass' | 'resos';
export type ActionTaken = 'booking_created' | 'booking_cancelled' | 'no_slots' | 'error';

export class EmailTrackingService {
  constructor(private supabase: SupabaseClient) {}

  async isProcessed(gmailMessageId: string): Promise<boolean> {
    const { data, error } = await this.supabase
      .from('processed_emails')
      .select('id')
      .eq('gmail_message_id', gmailMessageId)
      .limit(1);
    if (error) throw new Error(`isProcessed check failed: ${error.message}`, { cause: error });
    return !!data && data.length > 0;
  }

  async markProcessed(
    gmailMessageId: string,
    sourceType: SourceType,
    actionTaken: ActionTaken,
    bookingId: string | null = null,
    errorMessage: string | null = null,
    emailMetadata: { subject?: string; date?: string } = {},
  ): Promise<void> {
    let parsedEmailDate: string | null = null;
    if (emailMetadata.date) {
      const parsed = new Date(emailMetadata.date); // RFC 2822 header date carries its own timezone
      if (!isNaN(parsed.getTime())) parsedEmailDate = parsed.toISOString();
    }

    const { error } = await this.supabase
      .from('processed_emails')
      .insert({
        gmail_message_id: gmailMessageId,
        source_type: sourceType,
        action_taken: actionTaken,
        booking_id: bookingId,
        error_message: errorMessage,
        email_subject: emailMetadata.subject || null,
        email_date: parsedEmailDate,
      });

    if (error) {
      if (error.code === '23505') {
        // Unique constraint on gmail_message_id: a concurrent invocation won the race.
        log('WARN', 'Email already marked as processed (duplicate)', { gmailMessageId, actionTaken });
        return;
      }
      throw new Error(`markProcessed failed: ${error.message}`, { cause: error });
    }
    log('INFO', 'Email marked as processed', { gmailMessageId, sourceType, actionTaken, bookingId });
  }
}
