-- Insert a corporate event lead
INSERT INTO public.processed_leads (
    lead_id,
    lead_type,
    meta_submitted_at,
    form_type,
    form_id,
    created_time,
    platform,
    ad_id,
    full_name,
    email,
    phone_number,
    company_name,
    event_type,
    preferred_event_date,
    event_planning_timeline,
    expected_attendees,
    budget_per_person,
    raw_fields,
    spam_score,
    is_likely_spam
) VALUES (
    'LEAD_001',
    'corporate_event',
    NOW(),
    'corporate_inquiry',
    'FORM_001',
    NOW(),
    'facebook',
    'AD_123',
    'John Smith',
    'john.smith@company.com',
    '+65 9123 4567',
    'Tech Corp Pte Ltd',
    'Team Building',
    '2024-03-15',
    '3-6 months',
    '50-100',
    'SGD 150-200',
    '{"original_form_data": {"source": "facebook_lead_form", "campaign": "corporate_q1_2024"}}',
    0,
    false
);

-- Insert a social event lead
INSERT INTO public.processed_leads (
    lead_id,
    lead_type,
    meta_submitted_at,
    form_type,
    form_id,
    created_time,
    platform,
    full_name,
    email,
    phone_number,
    event_type,
    preferred_event_date,
    group_size,
    preferred_time,
    additional_inquiries,
    raw_fields,
    spam_score,
    spam_reasons,
    is_likely_spam
) VALUES (
    'LEAD_002',
    'social_event',
    NOW(),
    'birthday_inquiry',
    'FORM_002',
    NOW(),
    'website',
    'Sarah Lee',
    'sarah.lee@email.com',
    '+65 8765 4321',
    'Birthday Party',
    '2024-02-28',
    '10-15',
    'Evening',
    'Looking for a fun activity for my birthday celebration',
    '{"original_form_data": {"source": "website_form", "page": "birthday_events"}}',
    0,
    ARRAY[]::TEXT[],
    false
);

-- Insert a potentially spam lead
INSERT INTO public.processed_leads (
    lead_id,
    lead_type,
    meta_submitted_at,
    form_type,
    created_time,
    email,
    raw_fields,
    spam_score,
    spam_reasons,
    is_likely_spam
) VALUES (
    'LEAD_003',
    'unknown',
    NOW(),
    'contact_form',
    NOW(),
    'suspicious@spam.com',
    '{"original_form_data": {"source": "contact_form"}}',
    80,
    ARRAY['suspicious_email_domain', 'incomplete_information'],
    true
);
