name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: lengolf-email-automation
  REGION: asia-southeast1
  SERVICE_NAME: email-processor

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Create env.yaml
      env:
        PROJECT_ID: ${{ env.PROJECT_ID }}
        REGION: ${{ env.REGION }}
        FACEBOOK_SHEET_ID: ${{ secrets.FACEBOOK_SHEET_ID }}
        FACEBOOK_B2B_SHEET_ID: ${{ secrets.FACEBOOK_B2B_SHEET_ID }}
        LINE_TOKEN_CLASSPASS: ${{ secrets.LINE_TOKEN_CLASSPASS }}
        LINE_TOKEN_WEBRESOS: ${{ secrets.LINE_TOKEN_WEBRESOS }}
        LINE_TOKEN_FACEBOOK: ${{ secrets.LINE_TOKEN_FACEBOOK }}
        LINE_TOKEN_B2B: ${{ secrets.LINE_TOKEN_B2B }}
        LINE_TOKEN_B2C: ${{ secrets.LINE_TOKEN_B2C }}
        LABEL_CLASSPASS: "Web Leads (ClassPass)"
        LABEL_WEB: "Web Leads"
        LABEL_RESOS: "Web Leads (ResOS)"
        LABEL_FACEBOOK: "Web Leads (Facebook)"
        LABEL_COMPLETED: "Web Leads - completed"
      run: node scripts/setup-env.js
        
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --source . \
          --project ${{ env.PROJECT_ID }} \
          --region ${{ env.REGION }} \
          --env-vars-file env.yaml \
          --platform managed \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 2 \
          --service-account email-processor-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com \
          --timeout 540s

    - name: Create/Update Cloud Scheduler
      run: |
        SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --format 'value(status.url)')

        gcloud scheduler jobs create http process-emails \
          --schedule="*/10 * * * *" \
          --http-method=POST \
          --uri="${SERVICE_URL}/process" \
          --oidc-service-account-email="scheduler-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com" \
          --location=${{ env.REGION }} \
          --project=${{ env.PROJECT_ID }} \
          || gcloud scheduler jobs update http process-emails \
             --schedule="*/10 * * * *" \
             --http-method=POST \
             --uri="${SERVICE_URL}/process" \
             --oidc-service-account-email="scheduler-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com" \
             --location=${{ env.REGION }} \
             --project=${{ env.PROJECT_ID }}