name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  PROJECT_ID: lengolf-email-automation
  REGION: asia-southeast1
  SERVICE_NAME: email-processor
  DEPLOYER_SA: github-actions-deployer@lengolf-email-automation.iam.gserviceaccount.com
  PROCESSOR_SA: email-processor-sa@lengolf-email-automation.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Enable required APIs
      run: |
        echo "Enabling required APIs..."
        gcloud services enable run.googleapis.com
        gcloud services enable cloudscheduler.googleapis.com
        echo "Waiting for APIs to be fully enabled..."
        sleep 30
        
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        source: .
        env_vars: |
          PROJECT_ID=${{ env.PROJECT_ID }}
          REGION=${{ env.REGION }}
          FACEBOOK_SHEET_ID=${{ secrets.FACEBOOK_SHEET_ID }}
          FACEBOOK_B2B_SHEET_ID=${{ secrets.FACEBOOK_B2B_SHEET_ID }}
          LINE_TOKEN_CLASSPASS=${{ secrets.LINE_TOKEN_CLASSPASS }}
          LINE_TOKEN_WEBRESOS=${{ secrets.LINE_TOKEN_WEBRESOS }}
          LINE_TOKEN_FACEBOOK=${{ secrets.LINE_TOKEN_FACEBOOK }}
          LINE_TOKEN_B2B=${{ secrets.LINE_TOKEN_B2B }}
          LINE_TOKEN_B2C=${{ secrets.LINE_TOKEN_B2C }}
          LABEL_CLASSPASS=Web Leads (ClassPass)
          LABEL_WEB=Web Leads
          LABEL_RESOS=Web Leads (ResOS)
          LABEL_FACEBOOK=Web Leads (Facebook)
          LABEL_COMPLETED=Web Leads - completed
        flags: |
          --memory=512Mi
          --cpu=1
          --min-instances=0
          --max-instances=2
          --allow-unauthenticated
          --service-account=${{ env.PROCESSOR_SA }}
          --timeout=540s

    - name: Show Service URL
      run: echo "Service URL ${{ steps.deploy.outputs.url }}"

    - name: Setup Cloud Scheduler
      run: |
        echo "Creating/Updating Cloud Scheduler job..."
        # Delete existing job if it exists (ignore errors)
        gcloud scheduler jobs delete process-emails \
          --location=${{ env.REGION }} \
          --quiet || true
        
        # Create new job
        gcloud scheduler jobs create http process-emails \
          --schedule="*/10 * * * *" \
          --http-method=POST \
          --uri="${{ steps.deploy.outputs.url }}/process" \
          --oidc-service-account-email="scheduler-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com" \
          --location=${{ env.REGION }} \
          --project=${{ env.PROJECT_ID }}