name: Deploy to Cloud Run

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: lengolf-email-automation

      - name: Enable APIs
        run: |
          gcloud services enable run.googleapis.com
          gcloud services enable cloudscheduler.googleapis.com
          gcloud services enable secretmanager.googleapis.com
          sleep 30

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy email-processor \
            --source . \
            --platform managed \
            --region asia-southeast1 \
            --memory 512Mi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 2 \
            --allow-unauthenticated \
            --service-account email-processor-sa@lengolf-email-automation.iam.gserviceaccount.com \
            --timeout 540s \
            --set-env-vars="GOOGLE_CLOUD_PROJECT=lengolf-email-automation" \
            --set-env-vars="PROJECT_ID=lengolf-email-automation" \
            --set-env-vars="SUPABASE_URL=${{ secrets.SUPABASE_URL }}" \
            --set-env-vars="SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            --set-env-vars="FACEBOOK_SHEET_ID=${{ secrets.FACEBOOK_SHEET_ID }}" \
            --set-env-vars="FACEBOOK_B2B_SHEET_ID=${{ secrets.FACEBOOK_B2B_SHEET_ID }}" \
            --set-env-vars="LINE_TOKEN_CLASSPASS=${{ secrets.LINE_TOKEN_CLASSPASS }}" \
            --set-env-vars="LINE_TOKEN_WEBRESOS=${{ secrets.LINE_TOKEN_WEBRESOS }}" \
            --set-env-vars="LINE_TOKEN_FACEBOOK=${{ secrets.LINE_TOKEN_FACEBOOK }}" \
            --set-env-vars="LINE_TOKEN_B2B=${{ secrets.LINE_TOKEN_B2B }}" \
            --set-env-vars="LINE_TOKEN_B2C=${{ secrets.LINE_TOKEN_B2C }}" \
            --set-env-vars="META_ACCESS_TOKEN=${{ secrets.META_ACCESS_TOKEN }}" \
            --set-env-vars="META_PAGE_ID=${{ secrets.META_PAGE_ID }}" \
            --set-env-vars="META_B2B_FORM_ID=${{ secrets.META_B2B_FORM_ID }}" \
            --set-env-vars="META_B2C_FORM_ID=${{ secrets.META_B2C_FORM_ID }}" \
            --set-env-vars="LABEL_CLASSPASS=Web Leads (ClassPass)" \
            --set-env-vars="LABEL_WEB=Web Leads" \
            --set-env-vars="LABEL_RESOS=Web Leads (ResOS)" \
            --set-env-vars="LABEL_FACEBOOK=Web Leads (Facebook)" \
            --set-env-vars="LABEL_COMPLETED=Web Leads - completed" \
            --quiet